### ISSUE TITLE
Experiment with windows-based builds on Travis-CI

### ISSUE THREAD

**Issue by acoburn** [trellis-ldp/trellis#242]
This might be a suitable replacement for AppVeyor once support becomes more mature.

https://blog.travis-ci.com/2018-10-11-windows-early-release

**Comment by acoburn** [comment]
I have figured out how to get Travis-CI to do a Windows-based build of Trellis, but the CI process seems to hang at the completion of the `test` stage (i.e. after `./gradlew` completes). This is probably just due to the newness of Windows support. I will try again in a few months -- at which point, support will probably be much more robust.

The relevant configuration for this includes:

```yaml
jobs:
  allow_failures:
    - os: windows
  include:
    - name: "Windows"
      stage: test
      os: windows
      language: shell
      env: JAVA_HOME="/c/Program Files/Java/jdk1.8.0_192"
      script: ./gradlew check install
      before_cache: false
      cache: false
```

The `JAVA_HOME` value needs to match the actual version of Java that is installed, and this seems to keep changing; also, the cache does not appear to work, so it needs to be disabled for the build. It may be that moving the `JAVA_HOME` definition into a `before_script` block would make the most sense, as a script could scan the `C:\Program Files\Java` directory to find the correct value for `JAVA_HOME`. I also tried using `choco install jdk11`, but the process seemed to hang.
