### ISSUE TITLE
H2 database initialisation on first startup?

### ISSUE THREAD

**Issue by enridaga** [trellis-ldp/trellis#895]
I am following the documentation and trying to use release trellis-0.12 but on startup, I get a WARN message about a DB table not found. I am using h2 as I am just looking to play a bit with trellis, so I expected the DB schema to be setup on startup.

I did basic editing of the config.yml file:

```
# Database
database:
  # driverClass: org.mariadb.jdbc.Driver
  # driverClass: org.postgresql.Driver
  driverClass: ${TRELLIS_DB_DRIVER:-org.h2.Driver}

  # The database username
  user: ${TRELLIS_DB_USERNAME:-trellis}

  # The database password
  password: ${TRELLIS_DB_PASSWORD:-pwdhere}

  # The JDBC URL
  # url: jdbc:mysql://db.example.com/db-name
  # url: jdbc:postgresql://db.example.com/db-name
  url: ${TRELLIS_DB_URL:-jdbc:h2://.../trellis/trellis-0.12.1/database}
```

When I first start I get the following WARN message in the console log:

```
WARN  [2020-06-05 14:16:23,955] org.trellisldp.webac.WebAcService: Unable to auto-initialize Trellis: org.jdbi.v3.core.statement.UnableToCreateStatementException: org.h2.jdbc.JdbcSQLSyntaxErrorException: Table "EXTENSION" not found; SQL statement:
SELECT ext FROM extension WHERE resource_id = ? [42102-200] [statement:"SELECT ext FROM extension WHERE resource_id = ?", arguments:{positional:{0:0}, named:{}, finder:[]}]. See DEBUG log for more info
```
Looked into DEBUG logs on the server log file but I am not finding useful hints.

What's the best way to move forward?
